### ISSUE TITLE
ConfigRegistry is not thread safe

### ISSUE THREAD

**Issue by bastilw** [delphi-blocks/WiRL#25]
In Wirl.Core.Application the object FConfigRegistry is not thread safe. It's a simple TObjectList without CriticalSection or anything else.  the thread safe equivalent to FConfigRegistry is TWiRLConfigClassRegistry.Instance

**Comment by lminuti** [comment]
All WiRL registries are not thread safe and I think we doesn't change this behavior in the next releases. Generally the registry are used on the application startup in the mail thread. Using a critical section is not a good idea because you can have many simultaneous threads reading the registries and a critical sections serialize all these threads. 

Probably we can use TMultiReadExclusiveWriteSynchronizer but I'm not sure if it is worth the effort.
